[Unit]
Requires=android-super-map.service
After=android-super-map.service

[Service]
Environment=ANDROID_DATA_PART=/dev/disk/by-partlabel/userdata
Environment=ANDROID_SYSTEM_PART=/dev/disk/by-partlabel/system
Environment=ANDROID_VENDOR_PART=/dev/disk/by-partlabel/vendor
